#!/command/with-contenv sh
set -eu

exit_code=$1
signal=$2

if [ "$exit_code" -eq 256 ]; then
  exit_code=$((128 + signal))
fi

echo "$exit_code" > /run/s6-linux-init-container-results/exitcode
exec /run/s6/basedir/bin/halt
